flounder_qc_schemas <- list(
  sequencing_summary = c(
    "read_id",
    "channel",
    "start_time",
    "duration",
    "passes_filtering",
    "sequence_length_template",
    "mean_qscore_template",
    "barcode_arrangement"
  ),
  barcode_summary = c(
    "read_id",
    "barcode_arrangement",
    "barcode_score",
    "barcode_front_id",
    "barcode_rear_id"
  ),
  qc_run_summary = c(
    "schema_version",
    "source_id",
    "read_count",
    "passed_read_count",
    "failed_read_count",
    "pass_fraction",
    "total_bases",
    "passed_bases",
    "failed_bases",
    "mean_read_length",
    "median_read_length",
    "n50_read_length",
    "mean_qscore",
    "median_qscore",
    "channel_count",
    "first_read_start_time",
    "last_read_start_time",
    "run_duration_seconds",
    "barcode_count",
    "unclassified_read_count"
  ),
  qc_yield_over_time = c(
    "schema_version",
    "bin_start_seconds",
    "bin_end_seconds",
    "bin_start_minutes",
    "bin_end_minutes",
    "passes_filtering",
    "read_count",
    "bases",
    "cumulative_read_count",
    "cumulative_bases"
  ),
  qc_read_length_distribution = c(
    "schema_version",
    "read_length_bin_start",
    "read_length_bin_end",
    "passes_filtering",
    "read_count",
    "bases"
  ),
  qc_quality_distribution = c(
    "schema_version",
    "qscore_bin_start",
    "qscore_bin_end",
    "passes_filtering",
    "read_count",
    "bases"
  ),
  qc_channel_density = c(
    "schema_version",
    "channel",
    "read_count",
    "bases",
    "passed_read_count",
    "failed_read_count",
    "pass_fraction"
  ),
  qc_barcode_composition = c(
    "schema_version",
    "barcode_arrangement",
    "read_count",
    "bases",
    "passed_read_count",
    "failed_read_count",
    "read_fraction",
    "bases_fraction"
  ),
  qc_report_card = c(
    "schema_version",
    "check_id",
    "check_label",
    "status",
    "observed_value",
    "warn_threshold",
    "fail_threshold",
    "comparator",
    "details"
  ),
  ont_pod5_manifest = c(
    "file_name",
    "source_bucket",
    "source_key",
    "bytes",
    "last_modified_utc",
    "read_count",
    "state",
    "sha256"
  ),
  pod5_verify = c(
    "path",
    "size_bytes",
    "overall_status",
    "check",
    "category",
    "status",
    "detail"
  ),
  pod5_file_info = c(
    "path",
    "size_bytes",
    "flow_cell_id",
    "sequencing_kit",
    "read_count",
    "acquisition_start_utc",
    "duration_seconds",
    "pod5_version",
    "integrity_status",
    "integrity_reason"
  ),
  pod5_folder_info = c(
    "path",
    "pod5_file_count",
    "total_bytes",
    "total_reads",
    "flow_cell_ids",
    "sequencing_kits",
    "acquisition_start_utc",
    "acquisition_end_utc",
    "integrity_status",
    "integrity_reason",
    "failed_file_count",
    "verification_failed_count",
    "duplicate_file_names",
    "warnings"
  ),
  pod5_manifest = c(
    "schema_version",
    "source",
    "relative_path",
    "path",
    "size_bytes",
    "verification_status",
    "verification_failed_checks"
  ),
  pod5_compare = c(
    "status",
    "kind",
    "relative_path",
    "left_size_bytes",
    "right_size_bytes",
    "left_verification_status",
    "right_verification_status"
  ),
  pod5_subdivide_plan = c(
    "schema_version",
    "source",
    "strategy",
    "target",
    "chunk_index",
    "chunk_label",
    "file_count",
    "total_bytes",
    "read_count",
    "relative_paths",
    "warnings"
  ),
  bam_summary_status = c(
    "schema_version",
    "command",
    "path",
    "ok",
    "analysis_wall_seconds",
    "format",
    "mode",
    "confidence",
    "semantic_note"
  ),
  bam_summary_evidence = c(
    "schema_version",
    "header_used",
    "index_used",
    "records_scanned",
    "full_file_scanned"
  ),
  bam_summary_counts = c(
    "schema_version",
    "records_examined",
    "records_total_known",
    "mapped_records",
    "unmapped_records",
    "primary_records",
    "secondary_records",
    "supplementary_records",
    "duplicate_records",
    "qc_fail_records",
    "paired_records",
    "properly_paired_records",
    "read1_records",
    "read2_records"
  ),
  bam_summary_fractions = c(
    "schema_version",
    "scope",
    "fraction_mapped",
    "fraction_primary",
    "fraction_secondary",
    "fraction_supplementary",
    "fraction_duplicate",
    "fraction_qc_fail"
  ),
  bam_summary_mapq = c(
    "schema_version",
    "min",
    "max",
    "mean",
    "zero_count"
  ),
  bam_verify = c(
    "schema_version",
    "command",
    "path",
    "ok",
    "analysis_wall_seconds",
    "detected_format",
    "container",
    "is_bam",
    "shallow_verified",
    "deep_validated",
    "confidence",
    "checks_performed",
    "semantic_note",
    "error_code",
    "error_message",
    "error_detail",
    "error_hint"
  ),
  bam_check_eof = c(
    "schema_version",
    "command",
    "path",
    "ok",
    "analysis_wall_seconds",
    "detected_format",
    "bgzf_eof_present",
    "complete",
    "semantic_note",
    "error_code",
    "error_message",
    "error_detail",
    "error_hint"
  ),
  bam_check_index_status = c(
    "schema_version",
    "command",
    "path",
    "ok",
    "analysis_wall_seconds",
    "format"
  ),
  bam_check_index_index = c(
    "schema_version",
    "present",
    "selected_path",
    "kind",
    "support_level",
    "usable",
    "syntactically_valid",
    "stale",
    "bam_newer_than_index",
    "compatibility",
    "notes"
  ),
  bam_check_index_candidates = c(
    "schema_version",
    "path",
    "kind",
    "support_level",
    "exists"
  ),
  bam_check_map_status = c(
    "schema_version",
    "command",
    "path",
    "ok",
    "analysis_wall_seconds",
    "format",
    "mapping_status",
    "has_mapped_reads",
    "evidence_source",
    "confidence",
    "semantic_note"
  ),
  bam_check_map_index = c(
    "schema_version",
    "present",
    "kind",
    "used",
    "diagnostic_status",
    "diagnostic_detail"
  ),
  bam_check_map_summary = c(
    "schema_version",
    "references_defined",
    "references_with_mapped_reads",
    "total_mapped_reads",
    "total_unmapped_reads",
    "records_examined",
    "mapped_records_observed",
    "unmapped_records_observed",
    "references_with_mapped_reads_observed",
    "inconsistent_records_observed",
    "region_records_examined",
    "region_mapped_records_observed",
    "region_unmapped_records_observed"
  ),
  bam_check_map_references = c(
    "schema_version",
    "name",
    "length",
    "mapped_reads",
    "unmapped_reads",
    "observed"
  ),
  bam_check_sort = c(
    "schema_version",
    "command",
    "path",
    "ok",
    "analysis_wall_seconds",
    "format",
    "declared_so",
    "declared_ss",
    "declared_go",
    "observed_order",
    "observed_sub_order",
    "appears_sorted",
    "records_examined",
    "first_violation_record_index",
    "first_violation_reason",
    "evidence_strength",
    "header_matches_observation",
    "confidence",
    "semantic_note"
  ),
  bam_check_tag = c(
    "schema_version",
    "command",
    "path",
    "ok",
    "analysis_wall_seconds",
    "format",
    "tag",
    "required_type",
    "mode",
    "result",
    "tag_found",
    "records_examined",
    "records_with_tag",
    "full_file_scanned",
    "confidence",
    "semantic_note",
    "error_code",
    "error_message",
    "error_detail",
    "error_hint"
  ),
  bam_validate_status = c(
    "schema_version",
    "command",
    "path",
    "ok",
    "analysis_wall_seconds",
    "format",
    "mode",
    "valid",
    "semantic_note"
  ),
  bam_validate_summary = c(
    "schema_version",
    "header_valid",
    "records_examined",
    "full_file_examined",
    "errors",
    "warnings",
    "infos"
  ),
  bam_validate_findings = c(
    "schema_version",
    "severity",
    "scope",
    "code",
    "message",
    "record_index",
    "reference_name",
    "tag"
  ),
  bam_validate_error = c(
    "schema_version",
    "code",
    "message",
    "detail",
    "hint"
  )
)

expect_flounder_schema <- function(object, schema) {
  testthat::expect_true(
    schema %in% names(flounder_qc_schemas),
    info = paste("Unknown floundeR schema:", schema)
  )
  testthat::expect_named(object, flounder_qc_schemas[[schema]])
}
