# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate mean Phred score from an ASCII encoded phred string
#' 
#' FASTQ and BAM store per base qualities as an ASCII string. Accessory methods
#' in e.g. ShortRead allow for a sum of the numeric encoded scores; this is not
#' corrected for the log/linear so scores are synthetically boosted
#' - this simple method performs mean on the character level data ...
#'
#' @param qstring is an ASCII encoded Phred quality score
#'
#' @return mean phred scaled q-value
#'
#' @examples
#' sequence_quality("ABCDEFGH")
#'
#' @export
sequence_quality <- function(qstring) {
    .Call('_floundeR_sequence_quality', PACKAGE = 'floundeR', qstring)
}

#' Consume a FASTQ file and collate basic characteristic observations
#' 
#' This method is a fast C++ implementation of a FASTQ parser aimed to perform
#' a quick collation of summary_statistic information that may be used to make
#' decisions as to how FASTQ sequence collections are crafted.
#'
#' @return long long integer of read fastq bases
#'
#' @examples
#' fastq <- system.file("extdata", "example.fastq.gz", package = "floundeR")
#' fishy_fastq(fastq)
#'
#' @export
fishy_fastq <- function(fastq) {
    .Call('_floundeR_fishy_fastq', PACKAGE = 'floundeR', fastq)
}

