# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Consume a FASTQ file and collate basic characteristic observations
#' 
#' This method is a fast C++ implementation of a FASTQ parser aimed to perform
#' a quick collation of summary_statistic information that may be used to make
#' decisions as to how FASTQ sequence collections are crafted.
#'
#' @return long long integer of read fastq bases
#'
#' @examples
#' fastq <- system.file("extdata", "example.fastq.gz", package = "floundeR")
#' fishy_fastq(fastq)
#'
#' @export
fishy_fastq <- function(fastq) {
    .Call('_floundeR_fishy_fastq', PACKAGE = 'floundeR', fastq)
}

